#server settings
server:
  servlet:
    contextPath: /filemanager
    # Max file size.
    multipart:
      max-file-size: 1MB
      # Max request size.
      max-request-size: 10MB
  
  #Content Storage native/cloud
storage:
  mode: native
  
  #native storage document base
file:
  directory: /home/xbdxllxhi/Downloads/maktba/
  root: assets
  
  
  
  #Azure properties
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=cmscontent;AccountKey=bcjeYNYUSH+0LF3+hiZGhcVAYXAeTrn1kMA0VzOcPelpUHBdewA7RLHOpTXj8t8c7C8pt81Ys6TrC7q/CTBYzg==;EndpointSuffix=core.windows.net


clavis:
  security:
    api-config:
      whitelisted-urls:
        - /swagger-ui/*
        - /v3/api-docs/*
        - /public/*
        - /error/*
        - /*
    keycloak:
      url: http://localhost:8085
      realm: clavis-admin
      resource: clavis-backend
      credentials:
        secret: clavis-backend
  kafka:
    bootstrap-servers: localhost:9092
    keycloak-topic: keycloak-event

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${clavis.security.keycloak.realm}/realms/${clavis.keycloak.realm}
          jwk-set-uri: ${clavis.security.keycloak.url}/realms/clavis-admin/protocol/openid-connect/certs


logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG